<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BACLARK77-MAC1.local" name="All Consecutive Web Tests" tests="3" failures="3" timestamp="8 Jul 2014 16:20:25 GMT" time="55.266" errors="0">
  <testcase name="TestSetup_Test" time="10.078" classname="com.nbcuni.test.publisher.tests.Setup.TestSetup">
    <failure type="java.lang.AssertionError" message="failing test case">
      <![CDATA[java.lang.AssertionError: failing test case
	at com.nbcuni.test.publisher.tests.Setup.TestSetup.TestSetup_Test(TestSetup.java:41)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TestSetup_Test -->
  <testcase name="TestSetup_Test" time="5.804" classname="com.nbcuni.test.publisher.tests.Setup.TestSetup">
    <failure type="java.lang.AssertionError" message="failing test case">
      <![CDATA[java.lang.AssertionError: failing test case
	at com.nbcuni.test.publisher.tests.Setup.TestSetup.TestSetup_Test(TestSetup.java:41)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TestSetup_Test -->
  <testcase name="TestSetup_Test" time="6.027" classname="com.nbcuni.test.publisher.tests.Setup.TestSetup">
    <failure type="java.lang.AssertionError" message="failing test case">
      <![CDATA[java.lang.AssertionError: failing test case
	at com.nbcuni.test.publisher.tests.Setup.TestSetup.TestSetup_Test(TestSetup.java:41)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TestSetup_Test -->
</testsuite> <!-- All Consecutive Web Tests -->
