<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BACLARK77-MAC1.local" name="com.nbcuni.test.publisher.tests.Advertising.MPS.ImplementMPS" tests="1" failures="0" timestamp="30 Apr 2014 16:43:52 GMT" time="5.736" errors="1">
  <testcase name="ImplementMPS_TC2901" time="5.736" classname="com.nbcuni.test.publisher.tests.Advertising.MPS.ImplementMPS">
    <error type="java.lang.AssertionError" message="Imagine that a big scary bug was found here...">
      <![CDATA[java.lang.AssertionError: Imagine that a big scary bug was found here...
	at org.testng.Assert.fail(Assert.java:94)
	at com.nbcuni.test.publisher.tests.Advertising.MPS.ImplementMPS.ImplementMPS_TC2901(ImplementMPS.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
]]>
    </error>
  </testcase> <!-- ImplementMPS_TC2901 -->
</testsuite> <!-- com.nbcuni.test.publisher.tests.Advertising.MPS.ImplementMPS -->
